name: Build project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --immutable --immutable-cache --check-cache
    - name: Build project
      run: yarn build
    - name: Test Project
      run: yarn workspace @allurereport/reader test
